export const SEARCH_BY_TITLE = "SEARCH_BY_TITLE";
export const GETMOVIES_ALL = "GETMOVIES_ALL";
export const GETMOVIES_SUCCESS = "GETMOVIES_SUCCESS";

export const GETPEOPLE_ALL = "GETMOVIES_ALL";
export const GETPEOPLE_SUCCESS = "GETMOVIES_SUCCESS";
